### ISSUE TITLE
Allow the QueryView to be a PersistentActor

### ISSUE THREAD

**Issue by filosganga** [ovotech/akka-persistence-query-view#6]
Sometimes you want a `PersistentActor` to be also a view for another `PersistentActor`. At this time does not seem possible to do with `QueryView`.

**Comment by danischroeter** [comment]
Hmm I would not advice to do that because the resulting actor would be quiet complex - any persistent actor could create a view as a child if needed. 
What would be the use cases for such a construct?

**Comment by filosganga** [comment]
I had a case where it was making sense at the time, but I see your point, the persistent actor may have the view as a child. I am happy to scrap this issue.
