### ISSUE TITLE
Upgrade Akka to 2.5.x

### ISSUE THREAD

**Issue by filosganga** [ovotech/akka-persistence-query-view#9]
Akka 2.5.x brings some changes to the persistence query API. The most notable one is the new `EventEnvelope` with the `Offset` support.

Moving to Akka 2.5.x will drop the support to Akka 2.4.x. Not sure how do we want to proceed.

**Comment by danischroeter** [comment]
we already use a minimally modified version with akka 2.5 (only minor change with EventEnvelope / EventEnvelope2)
->could contribute that... but it would mean using another branch for akka-2.5 and different versions

**Comment by filosganga** [comment]
Thanks @danischroeter.

I think it makes probably sense to have a branch for akka-2.4 and akka-2.5 as the same will happen when akka-2.6 will be released.

Not sure how to manage different version release in a proper way, I have to look at some libs that already doing it.

**Comment by dpfeiffer** [comment]
@filosganga any updated on this?

**Comment by filosganga** [comment]
Fixed in https://github.com/ovotech/akka-persistence-query-view/commit/0a87e3359df07a32941991e9f662af8d6c6c584d
